resources = {'value_null': "value cannot be null or empty",
             'file_empty': "file is empty",
             'folder_empty': 'folder is empty',
             'format_invalid': 'provided format is invalid',
             'not_in_generating_set': 'provided values are not in generating set',
             'value_not_found': 'value not found',
             'no_overlap': 'values do not overlap',
             'not_identical': 'values are not identical',
             'not_a_subset': 'not a subset of parent set',
             'arguments_invalid': 'provided arguments are invalid',
             'structures_incompatible': 'structures are not compatible',
             'value_out_of_bounds': 'value is out of bounds',
             'canonical_policy_generation_failed' : 'canonical policy generation failed',
             'mud_file_action_invalid' : 'MUD file access-control action is invalid',
             'mud_file_has_local_ipaddress_details' : 'MUD file contains local IP address details',
             'get_semantic_difference_failed':'failed to compute semantic difference of policies',
             'specified_target_zone_invalid': 'specified target zone is invalid'}

